import Head from 'next/head'
import { useRouter } from 'next/router'
import loppemarkeder from '../data/loppemarkeder.json'
import styles from '../styles/Home.module.css'
import { date, day } from '../utils/formatters'

export default function Slug() {
  const router = useRouter()
  const { slug } = router.query
  const loppemarked = loppemarkeder.find(element => element.slug === slug)
  const days = loppemarked?.openingHours.map((o, key) => {
    return (
      <span>{day(o.from)}</span>
    )
  })
  console.log(days)
  return (
    <div className={styles.container}>
      <Head>
        <title>Loppemarked på {loppemarked?.place} - loppe.app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Loppemarked på {loppemarked?.place} {loppemarked?.openingHours.map((o, key) => {
            return (
              <span className={styles.date}>{day(o.from)} {date(o.from)}</span>
            )
          })}
        </h1>
      </main>
    </div>
  )
}