import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import loppemarkeder from '../data/loppemarkeder.json'
import { date, hoursMinutes } from '../utils/formatters'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Loppemarkeder - loppe.app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Loppemarkeder
        </h1>

        <p className={styles.description}>
          Oversikt over loppemarkeder i hele Norge
        </p>

        <div className={styles.input}>
          <input type='text' autoFocus placeholder='Søk på sted, fylke eller dato' />
        </div>

        <div className={styles.grid}>
          {loppemarkeder.map((l, key) => {
            return (
              <Link href={`/${l.slug}`}>
                <a className={styles.card}>
                <h2>{l.place} &rarr;</h2>
                <p>{l.organizer} arangerer loppemarked på {l.place}</p>
                {l.openingHours.map((o, key) => {
                  return (
                    <p>{date(o.from)} {hoursMinutes(o.from)} - {hoursMinutes(o.to)}</p>
                  )
                })}
                </a>
              </Link>
            )
          })}
        </div>
      </main>

      <footer className={styles.footer}>
          loppe.app
      </footer>
    </div>
  )
}
